config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_for :admins, skip: [:registrations], controllers: {sessions: 'admins/sessions'}

  namespace :admin do 
    root to: "admins#index"
    resources :admins
    resources :users, only: :index
    resources :posts, only: [:index, :show]
  end

  root to: "user/timeline#index"

  namespace :user do 
    get 'profile', to: "profile#show"
    get 'potential_to_follow', to: "profile#potential_to_follow"
    get 'following', to: "profile#following"
    get 'followers', to: "profile#followers"

    resources :posts, only: [:create, :destroy] do 
      member do
        post :like_toggle
      end
    end

    resources :users, only: :show
    resources :comments, only: [:create, :destroy]

    resources :room_messages
    resources :rooms

    post 'follow/:id', to: "subscriptions#follow", as: :follow
    post 'unfollow/:id', to: "subscriptions#unfollow", as: :unfollow
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :phone, :name, :avatar, presence: true

  has_one_attached :avatar
  has_many :posts
  has_many :comments
  
  has_many :followers_subscriptions, foreign_key: :followed_id, class_name: 'Subscription'
  has_many :followers, through: :followers_subscriptions, source: :followed_by

  has_many :following_subscriptions, foreign_key: :followed_by_id, class_name: 'Subscription'
  has_many :following, through: :following_subscriptions, source: :followed

  scope :potential_to_follow, -> (user) { where.not(id: user.following.pluck(:id)).where.not(id: user.id) }

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.order(id: :desc)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < UserController

  def create
    f_params = form_params.merge(user: current_user)
    @comment = Comment.new(f_params)
    @post = @comment.post

    if @comment.save
      redirect_to user_profile_path
    else
      render "user/profile/show"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post

    if @comment.destroy
      respond_to do |format|
        format.js { render "destroy" }
      end
    end
  end


  private

  def form_params
    params.require(:comment).permit(:body, :post_id)
  end

end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController
  skip_before_action :verify_authenticity_token, only: :like_toggle

  def create
    f_params = form_params.merge(user: current_user)

    @post = Post.new(f_params)
    @comment = Comment.new

    if @post.save
      redirect_to user_profile_path
    else
      render "user/profile/show"
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy

    redirect_to user_profile_path
  end

  def like_toggle
    post = Post.find(params[:id])
    like = Like.find_by(user: current_user, post: post)

    if like.present?
      like.destroy
      respond_to { |format| format.json { render json: { liked: false, likesCount: post.likes.count }}}
    else
      Like.create(user: current_user, post: post)
      respond_to { |format| format.json { render json: { liked: true, likesCount: post.likes.count }}}
    end
  end

  private

  def form_params
    params.require(:post).permit(:body)
  end

end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController

	def show
		@post = Post.new
    @comment = Comment.new
	end

  def potential_to_follow
    @potential_to_follow = User.potential_to_follow(current_user)
  end

  def following
    @following = current_user.following
  end

  def followers
    @followers = current_user.followers
  end
	
end

app/controllers/user/room_messages_controller.rb
class User::RoomMessagesController < UserController
  before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)
  
    RoomChannel.broadcast_to @room, @room_message

    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end
  end  

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < UserController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end  

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to user_rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to user_rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/controllers/user/subscriptions_controller.rb
class User::SubscriptionsController < UserController

	def follow
    user_to_follow = User.find_by(id: params[:id])

    Subscription.create(followed_by: current_user, followed: user_to_follow)

    redirect_to user_potential_to_follow_path
  end

  def unfollow
    user = User.find_by(id: params[:id])

    subscription = Subscription.find_by(followed_by: current_user, followed: user) 
    subscription.destroy

    redirect_to user_following_path
  end
	
end

app/controllers/user/timeline_controller.rb
class User::TimelineController < UserController

	def index
        @posts = Post.where(user_id: current_user.following.pluck(:id)).order(created_at: :desc)
        @comment = Comment.new
	end
	
end

app/controllers/user/users_controller.rb
class User::UsersController < UserController

	def show
    	@user = User.find(params[:id])
			@comment = Comment.new
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user

  def authenticate_user
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params
  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :name, :avatar])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/user/rooms/_form.html.erb
<%= simple_form_for @room, :url => url_for(:controller => 'rooms'), :method => 'post' do |form| %>
  <%= form.input :name %>
  <%= form.submit "Criar", class: 'btn btn-success' %>
<% end %>

app/views/user/rooms/_rooms.html.erb
<div class="mb-1">
  <%= link_to new_user_room_path, style: 'width: 100%;', class: 'btn mt-2 btn-primary' do %>
    Nova sala
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, user_room_url(room), style: 'text-align: center; background: rgba(0, 0, 0, 0.1);', class: ' mt-1 mb-1 nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    Nenhuma sala criada.
  </div>
<% end %>

app/views/user/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/user/rooms/index.html.erb
<h1>Sala de bate-papo</h1>
<%= render "user/shared/navigation_bar" %>
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h5 class="alert-heading">
        Adicione informações na salas das equipes cadastradas no sistema.
      </h5>

      <hr />

      <p>
        <small>Entre ou crie uma sala de bate-papo agora mesmo.</small>
      </p>
    </div>
  </div>
</div>

app/views/user/rooms/new.html.erb
<h1>
  Creating a room  
</h1>

<%= render partial: 'form' %>

app/views/user/rooms/show.html.erb
<h1 class="reload-page">
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container pb-2">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <%# <img src="<%= room_message.user.avatar %>
              <%= image_tag(room_message.user.avatar, class: "ui-w-100-forced rounded-circle mr-3", style: "width: 60px; height: 60px") %>
            </div>

            <div class="col" style="background: rgba(0, 0, 0, 0.1); border-radius: 10px;">
              <div class="message-content">
                <p class="mb-1 pt-1 ml-2">
                  <%= room_message.message %>
                </p>

                <div class="text-right pr-1">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for @room_message, :url => url_for(:controller => 'room_messages'), :method => 'post', remote: true do |form| %>
      <div class="input-group mb-3 mt-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>

<div class="d-none" data-role="message-template">
  <div class="chat-message-container" style="background: rgba(0, 0, 0, 0.1); border-radius: 10px;">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1 pt-1 ml-2" data-role="message-text"></p>

          <div class="text-right pr-1">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>