config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_for :admins, skip: [:registrations], controllers: {sessions: 'admins/sessions'}

  namespace :admin do 
    root to: "admins#index"
    resources :admins
    resources :users, only: :index
    resources :posts, only: [:index, :show]
  end

  root to: "user/timeline#index"

  namespace :user do 
    get 'profile', to: "profile#show"
    get 'potential_to_follow', to: "profile#potential_to_follow"
    get 'following', to: "profile#following"
    get 'followers', to: "profile#followers"

    resources :posts, only: [:create, :destroy] do 
      member do
        post :like_toggle
      end
    end

    resources :users, only: :show
    resources :comments, only: [:create, :destroy]

    resources :room_messages
    resources :rooms

    post 'follow/:id', to: "subscriptions#follow", as: :follow
    post 'unfollow/:id', to: "subscriptions#unfollow", as: :unfollow
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end
  

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end
  

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :body, presence: true

  def liked_by_user?(user)
    likes.where(user: user).present?
  end
end
  

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json(options)
    super(options).merge(user_avatar_url: user.avatar)
  end  
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :followed, class_name: 'User'
  belongs_to :followed_by, class_name: 'User'
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :phone, :name, :avatar, presence: true

  has_one_attached :avatar
  has_many :posts
  has_many :comments
  
  has_many :followers_subscriptions, foreign_key: :followed_id, class_name: 'Subscription'
  has_many :followers, through: :followers_subscriptions, source: :followed_by

  has_many :following_subscriptions, foreign_key: :followed_by_id, class_name: 'Subscription'
  has_many :following, through: :following_subscriptions, source: :followed

  scope :potential_to_follow, -> (user) { where.not(id: user.following.pluck(:id)).where.not(id: user.id) }

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

  def index
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin

  def authenticate_admin
    redirect_to new_admin_session_path unless current_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController
  skip_before_action :verify_authenticity_token, only: :like_toggle

  def create
    f_params = form_params.merge(user: current_user)

    @post = Post.new(f_params)
    @comment = Comment.new

    if @post.save
      redirect_to user_profile_path
    else
      render "user/profile/show"
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy

    redirect_to user_profile_path
  end

  def like_toggle
    post = Post.find(params[:id])
    like = Like.find_by(user: current_user, post: post)

    if like.present?
      like.destroy
      respond_to { |format| format.json { render json: { liked: false, likesCount: post.likes.count }}}
    else
      Like.create(user: current_user, post: post)
      respond_to { |format| format.json { render json: { liked: true, likesCount: post.likes.count }}}
    end
  end

  private

  def form_params
    params.require(:post).permit(:body)
  end

end

app/controllers/user/rooms_controller.rb
class User::RoomsController < UserController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end  

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to user_rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to user_rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < UserController

	def show
    	@user = User.find(params[:id])
			@comment = Comment.new
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user

  def authenticate_user
    redirect_to new_user_session_path unless current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/admins/_form.html.erb
<div class="card" style="background-color:#f6f6f6;">
  <div class="card-body">
    <%= form_with(model: [:admin, admin], local: true) do |f| %>
    <%= render "layouts/form_errors", record: admin %>
      <form>
        <div class="form-group">
          <label>Nome</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Email</label>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-row">
          <div class="col-6">
            <div class="form-group">
              <label>Senha</label>
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>
          <div class="col-6">
            <div class="form-group">
              <label>Confirmar Senha</label>
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        <%= link_to "Voltar", admin_admins_path, class: "btn btn-secondary ml-2"%>
      </form>
    <% end %>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<h2>Editar Administrador <%= @admin.id %></h2>

<%= render "form", admin: @admin%>

app/views/admin/admins/index.html.erb
<%= link_to("Novo Adminstrador", new_admin_admin_path, class: "btn btn-success mb-4") %>
<h4>Admins</h4><br>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Criado em</th>
      <th scope="col"></th>
      <th scope="col"></th>

    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <th scope="row"><%= admin.id %></th>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to "Editar", edit_admin_admin_path(admin), class: "btn btn-warning btn-sm" %></td>
        <td><%= link_to "Deletar", admin_admin_path(admin), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<h2>Novo Administrador</h2>

<%= render "form", admin: @admin%>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
  <%= image_tag("semb-white.png", alt: "logo", class: 'navbar-brand', style: "height:35px;")%>
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(admin_root_path)? "active" : "" %>">
        <%= link_to("Administradores", admin_root_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_admins_path)? "active" : "" %>">
        <%= link_to("Usuários", admin_users_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_posts_path)? "active" : "" %>">
        <%= link_to("Denúncias", admin_posts_path, class: "nav-link") %>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color: #fff;"><%= current_admin.email %></div>
        </li>
        <li class="nav-item">
          <%= link_to("Sair", destroy_admin_session_path, method: :delete, class: "nav-link") %>
        </li>
      <ul>
    </div>
  </div>
</nav>